#%RAML 1.0
title: kafka-consumption-sapi

types:
  orders: !include types/orders.raml
  orderCancellations: !include types/orderCancellations.raml
  failedMessages: !include types/failedMessages.raml

/orders:
  put:
    displayName: Create or update order data
    body:
      application/json:
        type: orders
        example: !include examples/orders.json
    responses:
      202:
        body:
          application/json:
            examples:
              message: Order request accepted.
  /cancellations:
    put:
      displayName: Create or update order data
      body:
        application/json:
          type: orderCancellations
          example: !include examples/orderCancellations.json
      responses:
        202:
          body:
            application/json:
              examples:
                message: Cancellation request accepted.
/failedMessages:
  put:
    displayName: Log failed messages
    body:
      application/json:
        type: failedMessages
        example: !include examples/failedMessages.json
    responses:
      200:
        body:
          application/json:
            examples:
              message: Failed messages logged.
